# Generated by Django 5.0 on 2026-03-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fix",
            name="files",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="fix",
            name="file_path",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="fix",
            name="patch",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("researching", "Researching"),
                    ("questions_pending", "Questions Pending"),
                    ("research_complete", "Research Complete"),
                    ("fix_proposed", "Fix Proposed"),
                    ("completed", "Completed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
