# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_issue_status_and_fix_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="fix",
            name="branch_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="fix",
            name="pr_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
