# Generated by Django 6.0.3 on 2026-03-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_fix_branch_name_pr_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="research_goal",
            field=models.TextField(blank=True, null=True),
        ),
    ]
