# Generated by Django 6.0.3 on 2026-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_add_issue_research_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="coverage_gap_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("researching", "Researching"),
                    ("questions_pending", "Questions Pending"),
                    ("research_complete", "Research Complete"),
                    ("research_failed", "Research Failed"),
                    ("fix_proposed", "Fix Proposed"),
                    ("completed", "Completed"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
