# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0005_add_research_coverage_gap_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="recommended_changes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
