# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_add_research_recommended_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="file_to_edit",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
