# Generated by Django 5.0 on 2026-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installation_id", models.BigIntegerField(unique=True)),
                ("repository_name", models.CharField(max_length=255)),
                ("owner", models.CharField(max_length=255)),
                ("installed_at", models.DateTimeField(auto_now_add=True)),
                ("understanding", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-installed_at"],
            },
        ),
    ]
