# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0001_add_github_installation"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubinstallation",
            name="raw_tree",
            field=models.TextField(blank=True, null=True),
        ),
    ]
