# Generated by Django 6.0.3 on 2026-03-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0002_githubinstallation_raw_tree"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubinstallation",
            name="chroma_collection_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="source_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("indexing", "Indexing"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="githubinstallation",
            name="style_md",
            field=models.TextField(blank=True, null=True),
        ),
    ]
