# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0003_add_source_status_style_chroma"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubinstallation",
            name="understanding_directories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
