# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0004_understanding_directories"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubinstallation",
            name="indexed_paths",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
